font_size 13.0
window_padding_width 8
font_family      JetBrainsMono Nerd Font
italic_font      auto
# bold_font        auto
bold_italic_font auto
include theme.conf
background_opacity 0.6
#hide_window_decorations yes
#confirm_os_window_close 0
#
# Tab bar sempre visibile
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1

# Colori tab bar
active_tab_foreground   #000
active_tab_background   #eee
active_tab_font_style   bold
inactive_tab_foreground #444
inactive_tab_background #999

# Template per il titolo del tab
#tab_title_template "{title}"

allow_remote_control yes
shell_integration enabled

tab_title_template "{user}@{host} [{remote_addr}]"
