general {
    lock_cmd = pidof hyprlock || hyprlock   # evita istanze multiple
    before_sleep_cmd = loginctl lock-session # blocca prima del suspend
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 2
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 5 || true
    on-resume = brightnessctl -r || true
}

listener {
    timeout = 120
    on-timeout = hyprlock
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 10800
    on-timeout = systemctl suspend
}
